---
# tasks file for config_mysql_masters
- name: Creates database for WebSite
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Create MySQL user for Replication
  mysql_user:
    name: "{{ mysql_replica_user }}"
    password: "{{ mysql_replica_password }}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    host: "{{ hostvars[item].ansible_default_ipv4.address }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ groups['db_slaves'] }}"
  tags: [ mysql ]

- name: Site config
  template:
    src: "my.cnf.j2"
    dest: "/etc/mysql/conf.d/mysql.cnf"
  notify: Restart MySQL

#- name: Download SQL Dump file
#  get_url:
#    client_key: /home/brm/.ssh/id_rsa_bitbucket_brm
#    force_basic_auth: yes
#    url_username: rus-bryl
#    url_password: Rfhf,fc1970
#    url: "https://bitbucket.org/websolab/eurofinance/src/master/wda_ef.2021-07-07.sql.gz"
#    dest: /tmp/dump.sql.gz


- name: Search for Database dump
  find:
    paths: /var/www/{{ project_name }}
    patterns: 'wda_ef.*.sql.gz'
  register: db_dump

- name: Copy db_dump file
  copy:
    remote_src: yes
    src: "{{ item.path }}"
    dest: /tmp/dump.sql.gz
  with_items: "{{ db_dump.files }}"

- name: Restore DataBase from dump file
  mysql_db:
    name: "{{ mysql_db }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: import
    target: /tmp/dump.sql.gz

#- name: Dump WebSite DB
#  mysql_db:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    name: "{{ mysql_db }}"
#    single_transaction: yes
#    state: dump
#    target: /tmp/dump.sql

#- name: Get binlog file and position
#  mysql_replication:
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    mode: getmaster
#  register: master

#- name: look for binlod file and position
#  debug:
#    msg: File- {{ master.File }} and Position- {{ master.Position }}

