---
# tasks file for config_mysql_masters
- name: Creates database for WebSite
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Create MySQL user for Replication
  mysql_user:
    name: "{{ mysql_replica_user }}"
    password: "{{ mysql_replica_password }}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    host: "{{ hostvars[item].ansible_default_ipv4.address }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop: "{{ groups['db_slaves'] }}"
  tags: [ mysql ]

- name: Site config
  template:
    src: "my.cnf.j2"
    dest: "/etc/mysql/conf.d/mysql.cnf"
  notify: Restart MySQL

- name: Clone Repo from Bitbucket
  git:
    repo: git@bitbucket.org:websolab/eurofinance.git
    key_file: /home/brm/.ssh/id_rsa_bitbucket_brm
    dest: /var/www/{{ project_name }}/
    version: master
    accept_hostkey: yes
    force: yes

- name: Search for Database dump
  find:
    paths: /var/www/{{ project_name }}
    patterns: 'wda_ef*.sql'
  register: db_dump

- name: Copy db_dump file
  copy:
    remote_src: yes
    src: "{{ item.path }}"
    dest: /tmp/dump.sql
  with_items: "{{ db_dump.files }}"

- name: Restore DataBase from dump file
  mysql_db:
    name: "{{ mysql_db }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: import
    target: /tmp/dump.sql

